package it.unirc.sapafi.enumerative;

public enum GraphType {
	DENSEGRAPH,
	DIRECTEDDENSEGRAPH,
	DIRECTEDSPARSEGRAPH,
	DIRECTEDWEIGHTEDDENSEGRAPH,
	DIRECTEDWEIGHTEDSPARSEGRAPH,
	SPARSEGRAPH,
	WEIGHTEDDENSEGRAPH,
	WEIGHTEDSPARSEGRAPH,
}
